name: core_notification
description: OneSignal push notification integration for Flutter app
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  onesignal_flutter: ^5.3.5
  riverpod_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  riverpod_generator: ^4.0.0+1
