name: web_app
description: Main web application
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Local packages (Melos が自動リンク)
  shared_ui:
  core_i18n:
  core_utils:
  core_auth:
  core_api:
  core_polar:
  core_game:
  core_genui:

  # Game engine (direct dep for TRPG feature components)
  flame: ^1.35.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State management
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^4.0.0

  # Navigation
  go_router: ^17.0.1

  # Backend integration
  supabase_flutter: ^2.10.3

  # API code generation
  swagger_parser: ^1.34.0

  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  intl: ^0.20.2

  # Data models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Widgetbook annotations for Use Case definitions
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.7.1
  riverpod_generator: ^4.0.0+1
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.12.0
  drift_dev: ^2.29.0

  # E2E Testing with Patrol
  patrol: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Patrol E2E Testing Configuration
patrol:
  app_name: Flutter Boilerplate
  android:
    package_name: com.example.web_app
  ios:
    bundle_id: com.example.webApp
  macos:
    bundle_id: com.example.webApp
